apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  labels:
    app: loan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: loan-service
          image: libraryhubackr.azurecr.io/loan-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: libraryhub-secrets
                  key: loan-database-url
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: libraryhub-config
                  key: LOAN_RABBITMQ_URL
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: libraryhub-config
                  key: LOAN_RABBITMQ_EXCHANGE
            - name: RABBITMQ_QUEUE_BOOK_RESERVED
              valueFrom:
                configMapKeyRef:
                  name: libraryhub-config
                  key: LOAN_RABBITMQ_QUEUE_BOOK_RESERVED
            - name: RABBITMQ_QUEUE_BOOK_OUT_OF_STOCK
              valueFrom:
                configMapKeyRef:
                  name: libraryhub-config
                  key: LOAN_RABBITMQ_QUEUE_BOOK_OUT_OF_STOCK
            - name: LOAN_DURATION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: libraryhub-config
                  key: LOAN_DURATION_DAYS
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 40
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
spec:
  selector:
    app: loan-service
  ports:
    - port: 8001
      targetPort: 8001


